Add screenshots and exercise to D
smartlyio/fullstack-hy2020.github.io pull request #7
Opened 2020-10-07 12:46 UTC by anna-osipova

2020-10-07 13:44 UTC, TomiHiltunen commented on src/content/11/en/part11d.md
> +### Exercise 11.6.
Exercise blocks should start with `<div class="tasks">` to get the look-n-feel that matches rest of the site.

2020-10-08 10:14 UTC, TomiHiltunen requested changes

2020-10-08 10:14 UTC, TomiHiltunen commented on src/content/11/en/part11d.md
> +<div class="content">
```suggestion
<div class="tasks">
```

2020-10-14 09:10 UTC, TomiHiltunen approved these changes

2020-10-14 10:22 UTC, antoinert approved these changes

2020-10-14 10:47 UTC, merged